// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_childSurv_TMBExports
#include <TMB.hpp>
#include "ll_rw.hpp"
#include "pe_rw.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "ll_rw") {
    return ll_rw(this);
  } else if(model == "pe_rw") {
    return pe_rw(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
